//
// Created by entakitos on 25/10/16.
//

#ifndef ANALIZADORLEXICO_DEFINES_H
#define ANALIZADORLEXICO_DEFINES_H


//Lexical components definitions
#define LITERAL_STRING 500
#define LITERAL_INTEGER 501
#define LITERAL_FLOAT 502
#define DOCUMENTATION_COMMENT 502
#define IDENTIFIER 503
#define TOKEN_ADDITION_ADDITION 508
#define TOKEN_EQUALS_EQUALS 512
#define TOKEN_ADDITION_EQUALS 513


#endif //ANALIZADORLEXICO_DEFINES_H
